theme = "snazzy"

[editor]
bufferline  = "never"
cursorline  = true
line-number = "absolute"
true-color  = true
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-messages = true

[editor.statusline]
left   = ["mode", "file-name", "spinner"]
center = ["version-control"]
right  = ["diagnostics", "workspace-diagnostics", "position"]
mode.insert = "INSERT"
mode.normal = "NORMAL"
mode.select = "SELECT"

[editor.whitespace.render]
space = "none"
tab   = "none"

[keys.normal]
tab     = ":bn"
"S-tab" = ":bp"
"esc"   = ["collapse_selection", ":w"]

[keys.select]
"esc" = ["collapse_selection", "normal_mode", ":w"]

[keys.insert]
"esc" = ["normal_mode", ":w"]
